### ISSUE TITLE
Attempting to load a non-RPL type of XML file will result in an unhandled exception

### ISSUE THREAD

**Issue by mdc88** [pdxPackrat/Projects#38]
When issuing a LOAD command for an XML file that is not of the RPL format, the program SHOULD handle the problem correctly but doesn't, it results in an unhandled exception (see details below).

**Comment by mdc88** [comment]
Stack trace: 

Unhandled Exception: System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderResourcePresentationList.Read6_ResourcePresentationList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at AcsListener.Program.LoadRplFromUrl(String rplUrlPath) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1163
   at AcsListener.Program.DoCommandLoad(String rplUrlPath) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 865
   at AcsListener.Program.CommandProcess(Object obj) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 328
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[02:26:00 INF] Thread #60: Connection Terminated
