### ISSUE TITLE
AcsListener has unhandled exception if something telnets to it on 4170 (other than the ACS device)

### ISSUE THREAD

**Issue by mdc88** [pdxPackrat/Projects#44]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Error: was expecting at least a 21-byte array for AnnounceResponse constructor
   at AcsListener.AcspAnnounceResponse..ctor(Byte[] inputArray) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\AcspAnnounceResponse.cs:line 41
   at AcsListener.Program.ProcessAnnounceRrp() in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1349
   at AcsListener.Program.ListenerProcess(Object obj) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1067
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by mdc88** [comment]
Pretty sure I fixed the last problem but now I have this one:

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.get_DataAvailable()
   at AcsListener.Program.ProcessGetNewLeaseRrp(UInt32 leaseSeconds) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1411
   at AcsListener.Program.ListenerProcess(Object obj) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1068
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AcsListener.Program.ListenerProcess(Object obj) in D:\Z\pdxPackrat\Projects\AcsListener\AcsListener\Program.cs:line 1078
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by mdc88** [comment]
See above for the second unhandled exception issue, which I am occassionally able to repeat.  Re-opening this issue so that it can be further addressed.

**Comment by mdc88** [comment]
Added two more catch blocks to ListenerProcess() method to handle the two scenarios that are occurring (where the NetworkStream object "stream" and the TcpClient object "ListenerClient", both static members of the Program class, are getting accessed by another thread after having been cleaned up).   I need to address the root cause of this issue still ( a race condition where the validity check is already passed by one thread before another thread hangs up the connection and disposes/nulls the objects.
